target 'TweakologyEngine_Example' do
  pod 'TweakologyEngine', :path => '../', :testspecs => ['Tests']
#  pod 'HTMLEntities', :git => 'https://github.com/IBM-Swift/swift-html-entities.git', :tag => '3.0.11'
  pod 'SDWebImage', '4.4.2', :modular_headers => true
  pod 'GCDWebServer', '3.4.2', :modular_headers => true
  pod 'STRFTimeFormatter', :git => 'https://github.com/brunophilipe/STRFTimeFormatter.git', :modular_headers => true

  target 'TweakologyEngine_Tests' do
    inherit! :search_paths
  end
end

